/***
    PARA CRIAR BANCO
    bd: automata4b
    us: app
    pw: app

    essas informações ficam configuradas em: tadsstore-spring\src\main\resources\application.properties
    não esquecer de selecionar o glassfish nas propriedades do banco Java DB: \Program Files\glassfish-4.1.1\javadb
***/

/*
    PRODUTO
    IMAGEM
    CATEGORIA
*/

CREATE TABLE TB_PRODUTO (
    ID_PRODUTO BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_PRODUTO PRIMARY KEY, 
    --NM_PRODUTO VARCHAR(100) NOT NULL,
    --DS_PRODUTO VARCHAR(1000) NOT NULL,
    --DT_CADASTRO TIMESTAMP NOT NULL,
    --VL_PRODUTO DECIMAL(18,2) NOT NULL
    DS_PRODUTO VARCHAR(100) NOT NULL,
    DS_DETALHES VARCHAR(1000) NOT NULL,
    DH_INCLUSAO TIMESTAMP NOT NULL,
    VL_PREUNI DECIMAL(18,2) NOT NULL
);

CREATE TABLE TB_IMAGENS (
    ID_IMAGEM BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_IMAGEM PRIMARY KEY,
--     DS_IMAGEM VARCHAR(100) NOT NULL,
--     DS_IMAGEM VARCHAR(100),
--     ID_PRODUTO BIGINT NOT NULL
    DS_NOME VARCHAR(100) NOT NULL,
    DS_IMAGEM VARCHAR(100),
    ID_PRODUTO BIGINT NOT NULL
);

ALTER TABLE TB_IMAGENS ADD CONSTRAINT FK_PRODUTO_IMAGEM FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

CREATE TABLE TB_CATEGORIA (
    ID_CATEGORIA INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_CATEGORIA PRIMARY KEY,
    --NM_CATEGORIA VARCHAR(100) NOT NULL
    DS_CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE TB_PRODUTO_CATEGORIA (
    PK_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT PK_PRODUTO_CAREGORIA PRIMARY KEY,
    ID_PRODUTO BIGINT NOT NULL,
    ID_CATEGORIA INT NOT NULL
);

ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);

ALTER TABLE TB_PRODUTO_CATEGORIA ADD CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA);

/**********************/

/*
    VENDA
    ESTOQUE
*/

CREATE TABLE TB_VENDA(
    PK_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1000, INCREMENT BY 1) CONSTRAINT PK_PRODUTO_CATEGORIA PRIMARY KEY,
    FK_COMPRADOR INT, /* CÓDIGO DO USUÁRIO */
    DT_VENDA TIMESTAMP,
    VL_PRODUTOS DECIMAL(18,2),
    VL_FRETE DECIMAL(18,2),
    VL_TOTAL DECIMAL(18,2),
    NR_PARCELAS INT,
    NR_PRAZOINI INT, /* DE ENTRAGA */
    NR_PRAZOFIM INT,
    DS_ENDERECO VARCHAR(60),
    DS_NUMERO VARCHAR(8),
    DS_BAIRRO VARCHAR(60),
    DS_COMPLEMETO VARCHAR(100),
    DS_CIDADE VARCHAR(50),
    DS_UF CHAR(2),
    DS_CEP VARCHAR(10),
    DS_FORMAPAG VARCHAR(30),
    DS_TRANSPORTADORA VARCHAR(60)
);

INSERT INTO TB_VENDA (FK_COMPRADOR, DT_VENDA, VL_PRODUTOS, VL_FRETE, VL_TOTAL, NR_PARCELAS, NR_PRAZOINI, NR_PRAZOFIM, DS_ENDERECO, DS_NUMERO, DS_BAIRRO, DS_COMPLEMETO, DS_CIDADE, DS_UF, DS_CEP, DS_FORMAPAG, DS_TRANSPORTADORA) 
VALUES (1, CURRENT_TIMESTAMP, 200, 20, 220, 3, 1, 5, 'PROF. CARLOS REIS', '39', 'PINHEIROS', 'CASA 02', 'SÃO PAULO', 'SP', '05424020', 'BOLETO', 'RELAMPAGO')