INSERT INTO TB_PRODUTO (DS_NOME, DS_DESCRICAORESUMIDA, DS_DESCRICAO, QT_ESTOQUE, VL_PRECO, DT_CADASTRO, DS_IMAGEM) VALUES (
'Processador Intel Core i3-7350k',
'Processador Intel Core i3-7350k Kaby Lake 7a Geração, Cache 4MB, 4.2GHz LGA 1151',
'Características',
0,
800,
CURRENT_TIMESTAMP,
'https://images6.kabum.com.br/produtos/fotos/88076/88076_index_gg.jpg'
)

;

INSERT INTO TB_PRODUTO (DS_NOME, DS_DESCRICAORESUMIDA, DS_DESCRICAO, QT_ESTOQUE, VL_PRECO, DT_CADASTRO, DS_IMAGEM) VALUES (
'Nobreak SMS 2200va mono 220v',
'Nobreak SMS 2200va mono 220v Power Vision - 27746 preto compacto',
'* Características: - Marca: SMS - Modelo: 27746 * Especificações: - Microprocessador: RISC/FLASH de alta velocidade - Comunicação Inteligente: padrões RS-232 e USB (acompanha cabo USB tipo A-B) - Tensão: Monovolt 220V',
0,
589.90,
CURRENT_TIMESTAMP,
'https://images8.kabum.com.br/produtos/fotos/75738/75738_index_gg.jpg'
)

;

INSERT INTO TB_IMAGENS (DS_NOME, DS_IMAGEM, ID_PRODUTO) VALUES 
('picture01.jpg', 'Imagem Placa de vídeo GTX 1080ti', 1),
('picture02.jpg', 'Processador intel i7 7700k', 2)

;

INSERT INTO TB_VENDA (FK_COMPRADOR, DT_VENDA, VL_PRODUTOS, VL_FRETE, VL_TOTAL, DS_ENDERECO, DS_NUMERO, DS_BAIRRO, DS_CIDADE, DS_CEP, DS_FORMAPAG) 
VALUES (1, CURRENT_TIMESTAMP, 200, 20, 220, 'PROF. CARLOS REIS', '39', 'PINHEIROS', 'SÃO PAULO', '05424020', 'BOLETO')

INSERT INTO TB_VENDA (FK_COMPRADOR, DT_VENDA, VL_PRODUTOS, VL_FRETE, VL_TOTAL, NR_PARCELAS, NR_PRAZOINI, NR_PRAZOFIM, DS_ENDERECO, DS_NUMERO, DS_BAIRRO, DS_COMPLEMETO, DS_CIDADE, DS_UF, DS_CEP, DS_FORMAPAG, DS_TRANSPORTADORA) 
VALUES (1, CURRENT_TIMESTAMP, 200, 20, 220, 3, 1, 5, 'PROF. CARLOS REIS', '39', 'PINHEIROS', 'CASA 02', 'SÃO PAULO', 'SP', '05424020', 'BOLETO', 'RELAMPAGO')