INSERT INTO TB_VENDA (FK_COMPRADOR, DT_VENDA, VL_PRODUTOS, VL_FRETE, VL_TOTAL, DS_ENDERECO, DS_NUMERO, DS_BAIRRO, DS_CIDADE, DS_CEP, DS_FORMAPAG) 
VALUES (1, CURRENT_TIMESTAMP, 200, 20, 220, 'PROF. CARLOS REIS', '39', 'PINHEIROS', 'SÃO PAULO', '05424020', 'BOLETO')

INSERT INTO TB_VENDA (FK_COMPRADOR, DT_VENDA, VL_PRODUTOS, VL_FRETE, VL_TOTAL, NR_PARCELAS, NR_PRAZOINI, NR_PRAZOFIM, DS_ENDERECO, DS_NUMERO, DS_BAIRRO, DS_COMPLEMETO, DS_CIDADE, DS_UF, DS_CEP, DS_FORMAPAG, DS_TRANSPORTADORA, DT_ALTERACAO, TG_STATUS) 
VALUES (1, CURRENT_TIMESTAMP, 200, 20, 220, 3, 1, 5, 'PROF. CARLOS REIS', '39', 'PINHEIROS', 'CASA 02', 'SÃO PAULO', 'SP', '05424020', 'BOLETO', 'RELAMPAGO', CURRENT_TIMESTAMP, 1)

insert into tb_itemvenda(FK_PRODUTO, FK_PEDIDO, QT_VENDA, VL_PREUNI, VL_TOTAL, DH_MOVIMENTO) VALUES (1, 1000, 2, 800, 1600, CURRENT_TIMESTAMP)
;
insert into tb_itemvenda(FK_PRODUTO, FK_PEDIDO, QT_VENDA, VL_PREUNI, VL_TOTAL, DH_MOVIMENTO) VALUES (2, 1000, 1, 589.9, 589.9, CURRENT_TIMESTAMP)
;

select * from tb_venda